<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
            font-family: sans-serif;
        }

        #sheet {
            border: 1px solid #efefef;
            height: fit-content;
            width: 538px;
            min-height: 20px;
            margin-top: 20px;
        }

        #sheet .sheet-row input:not(:first-child) {
            margin-left: -5px;
        }

        #sheet input {
            border: 1px solid silver;
            width: 100px;
            height: 15px;
            margin: 0;
            padding: 3px;
        }
    </style>
</head>

<body>

    <body>
        <button id="add-row">Add Row</button>
        <button id="remove-row">Remove Row</button>
        <button id="add-column">Add Column</button>
        <div id="sheet"></div>
        <script src="./55-event.js"></script>
    </body>
    <script>
        // // 三个状态：PENDING、FULFILLED、REJECTED
        // const PENDING = 'PENDING';
        // const FULFILLED = 'FULFILLED';
        // const REJECTED = 'REJECTED';

        // class Promise {
        //     constructor(executor) {
        //         // 默认状态为 PENDING
        //         this.status = PENDING;
        //         // 存放成功状态的值，默认为 undefined
        //         this.value = undefined;
        //         // 存放失败状态的值，默认为 undefined
        //         this.reason = undefined;

        //         // 调用此方法就是成功
        //         let resolve = (value) => {
        //             // 状态为 PENDING 时才可以更新状态，防止 executor 中调用了两次 resovle/reject 方法
        //             if (this.status === PENDING) {
        //                 this.status = FULFILLED;
        //                 this.value = value;
        //             }
        //         }

        //         // 调用此方法就是失败
        //         let reject = (reason) => {
        //             // 状态为 PENDING 时才可以更新状态，防止 executor 中调用了两次 resovle/reject 方法
        //             if (this.status === PENDING) {
        //                 this.status = REJECTED;
        //                 this.reason = reason;
        //             }
        //         }

        //         try {
        //             // 立即执行，将 resolve 和 reject 函数传给使用者  
        //             executor(resolve, reject)
        //         } catch (error) {
        //             // 发生异常时执行失败逻辑
        //             reject(error)
        //         }
        //     }

        //     // 包含一个 then 方法，并接收两个参数 onFulfilled、onRejected
        //     then(onFulfilled, onRejected) {
        //         console.log(this.status)
        //         if (this.status === FULFILLED) {
        //             onFulfilled(this.value)
        //         }

        //         if (this.status === REJECTED) {
        //             onRejected(this.reason)
        //         }
        //     }
        // }


        const PENDING = 'PENDING';
        const FULFILLED = 'FULFILLED';
        const REJECTED = 'REJECTED';

        class Promise {
            constructor(executor) {
                this.status = PENDING;
                this.value = undefined;
                this.reason = undefined;
                // 存放成功的回调
                this.onResolvedCallbacks = [];
                // 存放失败的回调
                this.onRejectedCallbacks = [];

                let resolve = (value) => {

                    if (this.status === PENDING) {
                        this.status = FULFILLED;
                        this.value = value;
                        // 依次将对应的函数执行
                        this.onResolvedCallbacks.forEach(fn => fn());
                    }
                }

                let reject = (reason) => {
                    if (this.status === PENDING) {
                        this.status = REJECTED;
                        this.reason = reason;
                        // 依次将对应的函数执行
                        this.onRejectedCallbacks.forEach(fn => fn());
                    }
                }

                try {
                    executor(resolve, reject)
                } catch (error) {
                    reject(error)
                }
            }

            then(onFulfilled, onRejected) {
                if (this.status === FULFILLED) {
                    onFulfilled(this.value)
                }

                if (this.status === REJECTED) {
                    onRejected(this.reason)
                }

                if (this.status === PENDING) {
                    // 如果promise的状态是 pending，需要将 onFulfilled 和 onRejected 函数存放起来，等待状态确定后，再依次将对应的函数执行
                    this.onResolvedCallbacks.push(() => {
                        onFulfilled(this.value)
                    });

                    // 如果promise的状态是 pending，需要将 onFulfilled 和 onRejected 函数存放起来，等待状态确定后，再依次将对应的函数执行
                    this.onRejectedCallbacks.push(() => {
                        onRejected(this.reason);
                    })
                }
            }
        }



        setTimeout(function () {
            console.log("123")
        }, 0)


        const promise = new Promise((resolve, reject) => {
            setTimeout(() => {
                console.info(123456)
                resolve('成功');
            }, 0)
        }).then(
            (data) => {
                console.log('success', data)
            },
            (err) => {
                console.log('faild', err)
            }
        )





    </script>
</body>

</html>